.github/workflows/skill_test_resources.yml
test/test_skill_resources.py

Updates tests to support current CommonPlay skill init behavior
As noted in a TODO, OCP messages might be updated to include skill_id in context

CommonPlay skill Resource Tests

---

.github/workflows/skill_test_intents.yml
test/test_skill_intents.py

Add negative intent tests to ensure an utterance does NOT match any skill intent. For example, one might check that "what is my physical address" doesn't match the IP intent.
Tested with [alerts skill](https://github.com/NeonGeckoCom/skill-alerts/pull/94) and [about skill](https://github.com/NeonGeckoCom/skill-about/pull/73)

Negative Intent Tests

---

.github/workflows/skill_test_installation.yml
.github/workflows/skill_test_intents.yml
.github/workflows/skill_test_resources.yml
.github/workflows/skill_tests.yml
test/test_skill_intents.py

Adds configuration options to negative intent tests to specify allowing medium/low confidence Padatious intents. In normal use, CommonQuery would handle requests before medium confidence and other fallbacks would handle requests before low confidence.
Includes `apt update` fix for skill test actions
Updates test logging to include DEBUG logs
Addressing test failures https://github.com/NeonGeckoCom/skill-stock/pull/35

Unmatched Intent Test Configuration

---

.github/workflows/propose_dated_release.yml
.github/workflows/propose_semver_release.yml
.github/workflows/publish_alpha_release.yml

Use `futureRelease` tag in changelogs to properly link generated GH tags/releases
Tested: https://github.com/NeonDaniel/neon-skill-utils/actions/runs/4694537617

Update changelog to include latest release and not just "unreleased"

---

.github/workflows/propose_dated_release.yml
.github/workflows/propose_semver_release.yml
.github/workflows/publish_alpha_release.yml

Pass maxIssues to Changelog action to limit changelog size
Noticed in [long-running automation in NeonCore](https://github.com/NeonGeckoCom/NeonCore/actions/runs/4694615607/jobs/8322944681)
Fix taken from [ovos-core automation](https://github.com/OpenVoiceOS/ovos-core/blob/dev/.github/workflows/publish_alpha.yml)

Add changelog_max_issues param to limit changelog contents

---

.github/workflows/propose_dated_release.yml
.github/workflows/propose_semver_release.yml
.github/workflows/publish_alpha_release.yml

Updates changelog action to include changes since the last release
Validated with neon_utils https://github.com/NeonDaniel/neon-skill-utils/actions/runs/4726379140/jobs/8385896423
This doesn't actually prevent github_changelog_generator from fetching a repo's entire history, so it will not solve any rate limiting errors (noted in [this issue](https://github.com/github-changelog-generator/github-changelog-generator/issues/993) as well as others in that project)

Add `sinceTag` to changelog generation

---

scripts/multiline_semantic_version_bump.py

Fix typo in multiline_semantic_version_bump.py in releasing next alpha version
Fixes bug introduced in #32 
Issue discovered in https://github.com/OpenVoiceOS/ovos-utils/actions/runs/4728398209
Tested: https://github.com/NeonDaniel/ovos_utils/actions
0.0.32 -> (alpha) 0.0.33a1 -> (minor) 0.1.0 -> (alpha) 0.1.1a1 -> (build) 0.1.1 -> (major) 1.0.0

Fix multiline alpha version handling

---

.github/workflows/license_tests.yml

Update shared license tests to accept excluded packages and licenses as inputs
Validated https://github.com/NeonGeckoCom/neon_metrics_service/pull/18

Update license tests to read exclusions from inputs

---

.github/workflows/docker_build_tests.yml
.github/workflows/license_tests.yml
.github/workflows/propose_dated_release.yml
.github/workflows/propose_semver_release.yml
.github/workflows/publish_alpha_release.yml
.github/workflows/publish_docker.yml
.github/workflows/publish_stable_release.yml
.github/workflows/pull_master.yml
.github/workflows/python_build_tests.yml
.github/workflows/skill_test_installation.yml
.github/workflows/skill_test_intents.yml
.github/workflows/skill_test_resources.yml
.github/workflows/skill_tests.yml
.github/workflows/skill_update_json_spec.yml
.github/workflows/skill_update_meta_repo.yml

Update workflows to allow callers to specify `runner`, i.e. for self-hosted runners
This initially is implemented to work around issues building the neon-speech Docker container
Validated https://github.com/NeonGeckoCom/neon_speech/pull/149

Enable non-default action runners

---

.github/workflows/skill_test_installation.yml
test/test_skill_osm_install.py

OSM tests are failing due to an upstream dependency bug and OSM/git installation is not recommended for most skills at this point anyways. 
This defaults to previous behavior that includes OSM tests, but allows for skipping OSM tests so future installation tests are not necessarily skipped
Validated https://github.com/NeonGeckoCom/skill-speak/actions/runs/4931628344/jobs/8813856059?pr=24

Make OSM tests optional

---

.github/workflows/skill_test_intents.yml
test/test_skill_intents.py

Adds options to specifically test against Padatious and Padacioso intent parsers. By default, only Padacioso tests are run as those better represent actionable changes to be made to intents.
Note that Adapt intents are tested in both cases, and if neither Padatios or Padacioso tests are specified then no intent tests will be run. Adapt intents are intended to run in both cases as those intent matches may be affected by any Padatious/Padacioso intents.
Validated https://github.com/NeonGeckoCom/skill-alerts/actions/runs/4932639106/jobs/8815854509

Better Padatious/Padacioso Test Specificaiton

---

scripts/requirements.txt

Fix failing skill.json automation by excluding cattrs version with dependency bug
https://github.com/python-attrs/cattrs/issues/369
Tested https://github.com/NeonGeckoCom/skill-user_settings/pull/87

Exclude cattrs 23.1.0 with dependency bug

---

.github/workflows/publish_alpha_release.yml
.github/workflows/publish_stable_release.yml

Adds `sdist` packaging to alpha and release automation
Tested [with neon-utils](https://github.com/NeonGeckoCom/neon-utils/pull/461)

Add sdist build to alpha and stable release actions

---

.github/workflows/python_build_tests.yml

Adds a second build test to check for any relative file paths in setup.py that will fail in other automations
[Failure tested](https://github.com/NeonGeckoCom/neon-tts-plugin-coqui-remote/actions/runs/5348150186/jobs/9697635213)
[Success tested](https://github.com/NeonGeckoCom/neon-tts-plugin-coqui-remote/actions/runs/5348183199/jobs/9697716217)

Add tests for relative paths in setup.py

---

.github/workflows/skill_test_intents.yml
.github/workflows/skill_tests.yml

Adds options to override python versions to test skills against ovos/neon cores (or disable tests for a particular core)
Also updates Neon tests to run against `master` branch
To disable tests for a particular core, pass an empty string and not an empty list
Backwards-compat validated https://github.com/NeonGeckoCom/skill-support_helper/actions/runs/5894424795/job/15988037070?pr=69
New behavior validated https://github.com/NeonGeckoCom/skill-support_helper/actions/runs/5894603041

Make python versions configurable per-core in skill test automation

---

.github/workflows/skill_test_resources.yml

Previous implementation assumed the skill package exists at the repo root
`skill_entrypoint` can be set to either a skill root directory or entrypoint specified in setup.py
https://github.com/NeonGeckoCom/skill-mark2-audio-receiver/pull/18

Allow calling workflow to specify skill entrypoint

---

.github/workflows/publish_docker.yml

Default to linux/amd64 but accept the comma-separated string of values that the action itself does
This will make it easier for developers (_cough_ me) to run Neon containers on their Apple Silicon Macs, but it also allows for any number of platform builds.
Validated at https://github.com/mikejgray/docker-testing

feat: extend to allow platforms

---

.github/workflows/docker_build_tests.yml
.github/workflows/publish_docker.yml

Update GHA versions to latest releases
Add optional `dockerfile` input for non-default dockerfiles
Add optional `build_args` input to support Docker build-args
Add caching to Docker builds
Closes #59 
https://github.com/NeonGeckoCom/neon-iris/pull/51 should be updated to use this shared action
Testing: https://github.com/NeonDaniel/neon-iris/actions/workflows/publish_test_build.yml

Update Docker Actions and Support `build-args`

---

.github/workflows/skill_test_intents.yml
test/test_skill_intents.py

Validated with:
https://github.com/NeonGeckoCom/skill-caffeinewiz/pull/69
https://github.com/NeonGeckoCom/skill-user_settings/pull/106
https://github.com/NeonGeckoCom/skill-date_time/pull/71

Update intent tests to use Minerva tests if available

---

.github/workflows/docker_build_tests.yml

Add option to run docker build tests on multiple platforms
Adds test support to go with https://github.com/NeonGeckoCom/.github/pull/62
Validated with https://github.com/NeonGeckoCom/neon_messagebus/pull/76

Update build tests to use buildx and support multiple platforms

---

.github/workflows/docker_build_tests.yml

Extends Docker build timeout to 60 minutes to account for multiple platform tests
https://github.com/NeonGeckoCom/NeonCore/actions/runs/7659582255/job/20876710245

Extend Docker build test timeout

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/workflows/get_issues.yml

Automatically aggregates all issues under the org on a weekly basis and outputs a csv file
Adds an automatic "Triage" label to any new issues created with a template
Relates to https://github.com/NeonGeckoCom/neon-docs/pull/47
- How can the generated output be parsed into something actionable?
- ~Should this run weekly rather than daily?~ Done.
- ~Can new issues be identified or flagged for triage?~ Label added.

Add weekly issue automation and add "Triage" label to new issues

---

.github/workflows/license_tests.yml

Update actions versions to latest stable
Make Python version configurable and update default to 3.12
Issue noted and fix validated: https://github.com/NeonGeckoCom/brainforge-webapp/actions/runs/12640463931/job/35220925786

Update license tests to use current actions and Python versions

---

.github/workflows/license_tests.yml

attrs is MIT licensed as indicated [on PyPI](https://pypi.org/project/attrs/) and [GitHub](https://github.com/python-attrs/attrs?tab=MIT-1-ov-file)
Validated change with https://github.com/OpenVoiceOS/ovos-PHAL-plugin-wallpaper-manager/actions/runs/13001758587/job/36261628131?pr=24

Whitelist attrs package

---

.github/workflows/license_tests.yml

[Per PyPI](https://pypi.org/project/RapidFuzz/) `RapidFuzz` carries an MIT license
Addresses [test failures](https://github.com/NeonGeckoCom/neon-messagebus-mq-connector/actions/runs/13778081973/job/38531174343?pr=56)

Exclude RapidFuzz from license tests by default

---

.github/workflows/license_tests.yml

`typing_extensions` uses the PSF license which applies to Python already, so should be allowed here
Validated with: https://github.com/NeonGeckoCom/neon-messagebus-mq-connector/actions/runs/14116049124/job/39546412794?pr=61

Whitelist `typing_extensions` in License tests

---

.github/workflows/license_tests.yml

`setuptools` is [MIT licensed](https://pypi.org/project/setuptools/)
`click` is [BSD-3 licensed](https://pypi.org/project/click/)
Validated with [skill-weather](https://github.com/NeonGeckoCom/skill-weather/actions/runs/15286374590/job/42997352590?pr=69)

Whitelist `click` and `setuptools`

---

.github/workflows/license_tests.yml

MIT license [per PyPI](https://pypi.org/project/typing-inspection/)
Validated with https://github.com/NeonGeckoCom/neon-data-models/actions/runs/15287195675/job/42999832701?pr=24

Whitelist `typing-inspection` with MIT license

---

scripts/oneline_semantic_version_bump.py

Adds support for updating timestamps in version files as part of semantic version bump automation
Implementation from https://github.com/NeonGeckoCom/pyklatchat-client/blob/c624522de7ea521621989de82f713753dd5e24ed/chat_client/version.py

Add support for "__version_ts__" timestamp in version_bump automation

---

.github/workflows/docker_build_tests.yml

Increase Docker Build tests timeout from 60 t0 120 Minutes
Timeout observed in [NeonCore Test Run](https://github.com/NeonGeckoCom/NeonCore/actions/runs/16976026627/job/48129025364?pr=750)
- Validated with: https://github.com/NeonGeckoCom/NeonCore/actions/runs/16980082287/job/48138065323

Increase Docker build test timeout
