.github/workflows/docker_build_tests.yml
.github/workflows/license_tests.yml
.github/workflows/publish_alpha_release.yml
.github/workflows/publish_docker.yml
.github/workflows/publish_stable_release.yml
.github/workflows/pull_master.yml
.github/workflows/python_build_tests.yml

Adds common GitHub workflows to avoid duplication across multiple repositories
Includes:
- Docker Build Tests
- License Tests
- Alpha Release Publication
- Docker Image Publication
- Stable Release Publication
- Draft Pull Request

Add common GH Workflows

---

.github/workflows/publish_docker.yml

Fix docker tag checks per https://stackoverflow.com/questions/71045674/how-to-check-if-an-optional-workflow-dispatch-input-is-set-or-not
Validated:
https://github.com/NeonGeckoCom/neon_speech/actions/runs/4198851053/jobs/7283005686
https://github.com/NeonGeckoCom/neon_messagebus/actions/runs/4198830178

Fixes docker tag null checks

---

.github/workflows/skill_tests.yml
.github/workflows/skill_update_json_spec.yml
.github/workflows/skill_update_meta_repo.yml

Add standard skill workflows:
- Skill Tests
- Skill JSON updates
- Skill meta repo updates
Validated with about skill https://github.com/NeonGeckoCom/skill-about/pull/60

Add Skill Workflows

---

.github/workflows/publish_alpha_release.yml
.github/workflows/skill_update_json_spec.yml
scripts/requirements.txt
scripts/update_skill_json.py
scripts/version_bump.py

Implement shared skill.json update script
Implement shared version_bump script
Update automations to use shared scripts
Testing in https://github.com/NeonGeckoCom/skill-about/pull/66
Validated https://github.com/NeonGeckoCom/neon-mana-utils/pull/20

Implement shared version_bump and skill.json scripts

---

.github/workflows/publish_alpha_release.yml
.github/workflows/skill_update_json_spec.yml

Fix branch ref to use default for checking out this repo in automations
Fixes #6

Fix branch ref for github repo checkout

---

.github/workflows/publish_alpha_release.yml

cd into the package repo so packages are accurately included in distributions

cd into build directory to fix setup.py references

---

.github/workflows/skill_test_installation.yml
test/test_skill_osm_install.py

Add test for skill installation via OSM

Add OSM Installation Tests

---

.github/workflows/skill_test_resources.yml
test/test_skill_resources.py

Adds logging to unit test failure cases
Handle empty lines in skill regex files
Resolve bugs found in https://github.com/NeonGeckoCom/skill-date_time/pull/41

Improved Skill Unit Tests

---

.github/workflows/skill_test_intents.yml
test/test_skill_intents.py

Add utterance log to failing intent tests to help diagnose issues
Debugging failure in [Device Control Center](https://github.com/NeonGeckoCom/skill-device_controls/pull/53/commits/987ea55484bff2fbfd86992ce5a8f2f5d3ba055d)

Log failing utterance in intent tests

---

.github/workflows/skill_test_resources.yml
test/test_skill_resources.py

Adds logging of dialog files tested when an item fails to resolve
Also adds logging of missing events
Troubleshooting [test failures](https://github.com/NeonGeckoCom/skill-launcher/pull/38)

Add logging to resource tests

---

.github/workflows/publish_alpha_release.yml

Add automation to tag alpha releases as GH prereleases
Make alpha branch configurable in automation

Tag Alpha Releases

---

scripts/dated_version_bump.py

Update dated versions to increment alpha until stable release instead of resetting daily
This means alpha versions can be used to track the number of alpha releases since the last stable release

Update dated version alpha handling

---

.github/workflows/publish_docker.yml

Moving changes around to test updated automation
https://github.com/NeonGeckoCom/neon_messagebus/actions/runs/4546056181
Testing https://github.com/NeonGeckoCom/.github/pull/20

Pull changes to branch under the org for testing

---

.github/workflows/publish_docker.yml

Testing automation changes

---

.github/workflows/skill_test_intents.yml
test/test_skill_intents.py

Adds a test method for Common Query handlers

Add Common Query intent tests

---

.github/workflows/skill_test_intents.yml
test/test_skill_intents.py

Adds a safe default value for non-CommonQuery skills
Fixes bug introduced in #27

Add default (null) value for CommonQuery test config

---

.github/workflows/publish_docker.yml

Fixes a typo in docker action output

Fix typo in docker automation output

---

.github/workflows/skill_test_intents.yml

Make intent test timeout configurable

Make intent test timeout configurable

---

.github/workflows/propose_dated_release.yml
.github/workflows/propose_semver_release.yml
.github/workflows/publish_alpha_release.yml
.github/workflows/publish_stable_release.yml
scripts/dated_version_bump.py
scripts/semantic_version_bump.py

Add actions to propose a stable release version (semver and dated)
Updates alpha release action to include new version in commit comment
Dated release tested: https://github.com/NeonDaniel/NeonCore/actions/runs/4681235101
Semver release tested: https://github.com/NeonDaniel/neon-skill-utils/actions/workflows/propose_release.yml

Stable Version Automation

---

scripts/dated_version_bump.py

Fix bug causing alpha versions to reset to '1' for dated alpha releases
Fixes issue introduced in #30

Fix logical error in dated version alpha releases

---

.github/workflows/pull_master.yml

Accept optional params for PR title, body, draft, and destination
Remove default values
Validated with: https://github.com/NeonDaniel/neon-skill-utils/pull/23 and https://github.com/NeonDaniel/neon-skill-utils/pull/24

Accept args to `pull_master` automation for created PR

---

.github/workflows/publish_alpha_release.yml

Fixes a script name error in `publish_alpha_release.yml` workflow
Fixes a missed refactor from #32

Fix alpha release bug

---

.github/workflows/publish_alpha_release.yml

Update alpha workflow to enable PyPI publishing after skipped changelog generation

Fix automation dependencies

---

scripts/oneline_semantic_version_bump.py

Fixes typo causing a minor version update instead of patch when releasing a new alpha
https://github.com/NeonGeckoCom/NeonCore/actions/runs/4760176127

Fix typo in alpha release action

---

.github/workflows/docker_build_tests.yml
.github/workflows/publish_docker.yml

Adds explicit Buildx installation to Docker workflow for self-hosted Actions runners
Adds optional QEMU setup to docker build actions
https://github.com/NeonGeckoCom/neon_speech/actions/runs/4884833363
Tested https://github.com/NeonDaniel/neon_speech/actions/workflows/publish_test_build.yml

Support docker qemu and Buildx

---

scripts/dated_version_bump.py

Fix logical error preventing stable dated release versions
https://github.com/NeonGeckoCom/NeonCore/actions/runs/4951033816

Fix logical error in dated_version_bump.py

---

.github/workflows/python_build_tests.yml

Add optional pip audit automation to python build tests

---

.github/workflows/propose_semver_release.yml
.github/workflows/publish_alpha_release.yml

Adds an optional script to run on version change. This can be used to update other version references within the package.
Validated https://github.com/NeonDaniel/neon-diana-utils/actions

Add optional script to run on version changes

---

.github/workflows/publish_alpha_release.yml
.github/workflows/publish_stable_release.yml

Update to handle `PYPI_TOKEN` passed explicitly vs inherited from org
https://github.com/OpenVoiceOS/ovos-PHAL-plugin-alsa/actions/runs/5284434815
https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

Update PyPI token secret handling

---

.github/workflows/publish_alpha_release.yml

Updates `publish_alpha_release` for use with OVOS packages
Validated with: https://github.com/NeonDaniel/ovos-PHAL-plugin-alsa/actions/runs/5285305317/jobs/9563665328

Update Alpha automation to support OVOS-style versioning

---

.github/workflows/publish_alpha_release.yml

Fixes logic error in alpha version bump action
https://github.com/NeonGeckoCom/skill-date_time/actions/runs/5285385879/jobs/9583693064

Add quotes to `alpha_var` check to handle unset variable

---

.github/workflows/skill_test_intents.yml
.github/workflows/skill_test_resources.yml
.github/workflows/skill_tests.yml
.github/workflows/skill_update_json_spec.yml

Patching PyYaml installation bug around dependency installation
https://github.com/yaml/pyyaml/issues/724
An updated OSM will allow installing pyyaml~=6.0 which is another solution here

Patch PyYaml installation bug

---

.github/workflows/skill_test_intents.yml
test/test_skill_intents.py

Fix config handling for secondary language tests
Backwards-compat validated https://github.com/NeonGeckoCom/skill-about/actions/runs/6126328368?pr=79
New behavior validated https://github.com/NeonGeckoCom/skill-date_time/actions/runs/5883098235

Fix secondary language intent tests

---

.github/workflows/skill_test_intents.yml
.github/workflows/skill_test_resources.yml
.github/workflows/skill_tests.yml

Add minimum ovos-core version to speed up dependency resolution error exceptions
Add support for skill `test` extra dependencies for unit tests

Update skill tests

---

.github/workflows/skill_test_resources.yml

Fix test skill loading in resource tests
Continuation of #64

Add entrypoint to skill resource tests

---

.github/workflows/skill_test_intents.yml
test/test_skill_intents.py

Add default Padatious config to scope tests to skill code
Issue noted in https://github.com/NeonGeckoCom/skill-date_time/actions/runs/7391640552/job/20108770514
Apprently introduced by https://github.com/OpenVoiceOS/ovos-config/pull/78/files#r1439966369
Fixes validated with https://github.com/NeonGeckoCom/skill-date_time/actions/runs/7392024788/job/20109907139

Patch config bug in ovos-core Skill Intent tests

---

.github/CONTRIBUTING.md

Add Default Contributing Document

---

.github/workflows/skill_tests.yml

This should speed things up pretty dramatically across a number of tests running in parallel. I also bumped the versions of the GitHub actions to latest, which I've been using in numerous other repos for months without issues.
None that I know of

feat: introduce pip caching into skill test execution

---

.github/workflows/skill_test_intents.yml

Removes deprecated Python versions from defaults
Tested: https://github.com/NeonGeckoCom/skill-core_ready/pull/11

Update Python versions used in intent tests

---

.github/workflows/license_tests.yml

Whitelist `audioread` with MIT license https://pypi.org/project/audioread/
- Tested with https://github.com/NeonGeckoCom/neon_speech/actions/runs/14363786850/job/40271621752?pr=210

Update license test excluded packages

---

.github/workflows/license_tests.yml

Whitelist urllib3 with MIT license (https://pypi.org/project/urllib3/)
Validated with https://github.com/NeonGeckoCom/neon_messagebus/actions/runs/14409669500/job/40414418535?pr=90

Update license_tests whitelist

---

.github/workflows/license_tests.yml

Update to latest release of action-pip-license-checker
Remove excluded packages that have been added to resolve previous Errors
Validated with [neon-core](https://github.com/NeonGeckoCom/NeonCore/actions/runs/16482464717/job/46599997813)

Update license_tests to use newer shared action
